version: '3'

networks:
  net:
    driver: bridge


services:
  json:
    build:
      dockerfile: Dockerfile.common
    networks:
      - net
    command:
      uvicorn main:app --host "json" --port 8080
  yaml:
    build:
      dockerfile: Dockerfile.common
    networks:
      - net
    command:
      uvicorn main:app --host "yaml" --port 8088
  msgpack:
    build:
      dockerfile: Dockerfile.common
    networks:
      - net
    command:
      uvicorn main:app --host "msgpack" --port 8089
  xml:
    build:
      dockerfile: Dockerfile.common
    networks:
      - net
    command:
      uvicorn main:app --host "xml" --port 8090
  avro:
    build:
      dockerfile: Dockerfile.common
    networks:
      - net
    command:
      uvicorn main:app --host "avro" --port 8091
  proto:
    build:
      dockerfile: Dockerfile.common
    networks:
      - net
    command:
      uvicorn main:app --host "proto" --port 8092

  proxy:
    build:
      dockerfile: Dockerfile.common
    networks:
      - net
    ports:
      - 2000:2000/udp
    environment:
      PROXY_HOST: "proxy"
      PROXY_PORT: "2000"
      CLIENT_PORT: "2001"
      CLIENT_HOST: "client"
    command:
      python3 proxy.py
    depends_on:
      - json
      - yaml
      - xml
      - msgpack

  client:
    build:
      dockerfile: Dockerfile.common
    networks:
      - net
    ports:
      - 2001:2001/udp
    environment:
      CLIENT_HOST: "client"
      PROXY_PORT: "2000"
      CLIENT_PORT: "2001"
      PROXY_HOST: "proxy"
    depends_on:
      - proxy
    command:
      python3 client.py
