FROM python:3.9
RUN mkdir /app
WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

COPY . .

ENV PYTHONPATH "${PYTHONPATH}:/app/serializers"
CMD ["python3", "client.py"]
